### ISSUE TITLE
Input field doesn't reseize with lot's of tokesn

### ISSUE THREAD

**Issue by nickboucart** [ajduke/meteor-boostrap-tokenfield#3]
Hi,

Just a quick question: I'm using this bootstrap tokenfield in an app of mine, and when I have a more tokens than the width of the field, the input field does not automatically adjusts in size, ie. become multiline... I was wondering if you experienced something similar. All the demo's I see do not have that behavior. 

Do you experience something similar?
thanks!
nick.

**Comment by ajduke** [comment]
Sorry for delay in response.

I guess thats the expected behavior of library.
I checked out again few demos of library on official page, http://sliptree.github.io/bootstrap-tokenfield/, it seems to be working as multi-line only.

If you want something different than this, you can discuss in official repo of same- https://github.com/sliptree/bootstrap-tokenfield. This current repo is meteor port of library.

Thanks and Regards,
/ajduke

**Comment by nickboucart** [comment]
Thanks for coming back to this.

In the mean time, I did find my issue, I had a css rule somewhere that
prevented by input field to grow bigger, so nothering to do with the
tokenfield code.

Thanks!
nick.
